name: Esegui Gen.py ogni 30 minuti

on:
  schedule:
    - cron: '*/30 * * * *'  # Esegue ogni 30 minuti
  workflow_dispatch:  # Permette di eseguire manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Sostituisci con la versione necessaria

      - name: Installa le dipendenze
        run: pip install requests

      - name: Esegui lo script
        run: python Gen.py

      - name: Aggiungi il file generato al commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output.txt  # Sostituisci con il nome del file che vuoi salvare
          git commit -m "Aggiungi file generato"
          
      - name: Pusha il cambiamento
        run: git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
